#define DYNAMIC_KEYMAP_LAYER_COUNT 8
#define NO_AUTO_SHIFT_ALPHA
#define ONESHOT_TIMEOUT 5000

#define TAPPING_TERM 200
#define SMTD_GLOBAL_RELEASE_TERM 10
#define MAX_DEFERRED_EXECUTORS 10
#define SMTD_GLOBAL_SEQUENCE_TERM 50
