/* SPDX-License-Identifier: GPL-2.0-or-later */
#pragma once

#define DYNAMIC_KEYMAP_LAYER_COUNT 8
#define RGB_MODS_INDICATOR_ENABLE
#define RGB_LAYER_INDICATOR_ENABLE
#define RGB_INDICATOR_BRIGHTNESS 5
#define RGB_TRIGGER_ON_KEYDOWN
#define NO_AUTO_SHIFT_ALPHA
#define ONESHOT_TIMEOUT 5000

#define TAPPING_TERM 200
#define SMTD_GLOBAL_RELEASE_TERM 10
#define MAX_DEFERRED_EXECUTORS 10
#define SMTD_GLOBAL_SEQUENCE_TERM 50

